name: 11 - Working with Inputs

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        default: false
      target:
        type: environment
        description: "Which environment the workflow will target"
      tag:
        type: choice
        options: [v1, v2, v3]
        default: v3
        description: "Release from which to build and deploy"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: |
          echo "Building from tag ${{ github.event.inputs['tag']}}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event.inputs['dry-run'] == 'false' && github.event.inputs['target'] == github.event.inputs['tag'] }}
    
    steps:
      - name: Deploy
        run: |
          echo "Deploying to ${{ github.event.inputs['tag']}}"
          
