name: 12 - Working with Outputs

on:
    workflow_dispatch:
        inputs:
            build-status:
                type: choice
                options: [success, failure]
                default: 'success'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print GITHUB_OUTPUT path
      #GITHUB_OUTPUT is a special environment variable that can be used to store outputs
        run: echo "Building from tag ${{ inputs['tag']}}"


      - name: Build
        run: echo "GITHUB_OUTPUT variable: "status=<retrieve the value of the build-status input here>""
