name: 16 - Working with Environments

on:
  workflow_dispatch:
    inputs:
      target-env:
        description: 'target-env'
        type: environment
        default: 'staging'

# Set the run-name dynamically using the target-env input
run-name: 16 - Working with Environments | env - ${{ github.event.inputs.target-env }}

jobs:
  echo:
    runs-on: ubuntu-latest

    # Set sf the environment parameter dynamically based on the target-env input
    environment: ${{ inputs.target-env }}
    env:
      # Dynamically set my_env_value based on the selected environment (prod or staging)
      my_env_value: ${{ vars.MY_ENV_VALUE || 'default value' }}

    steps:
      # Step 1: Define environment variable and echo it
      - name: Echo vars
        run: |
          echo "Env variable: ${{ env.my_env_value }}"
