name: 16 - Working with Environments

on:
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    # Set sf the environment parameter dynamically based on the target-env input
    environment: staging
    env:
      # Dynamically set my_env_value based on the selected environment (prod or staging)
      my_env_value: ${{ vars.MY_ENV_VALUE || 'default value' }}

    steps:
    # Step 1: Define environment variable and echo it
      - name: Echo vars
        run: |
          echo "Deploy to staging..."

  e2e-tests:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: E2E tests
        run: echo "Running E2e tests..."

  deploying-prod:
    needs: e2e-tests
    runs-on: ubuntu-latest
    # Set sf the environment parameter dynamically based on the target-env input
    environment: prod
    env:
      # Dynamically set my_env_value based on the selected environment (prod or staging)
      my_env_value: ${{ vars.MY_ENV_VALUE || 'default value' }}
    steps:
      # Step 1: Define environment variable and echo it
      - name: Echo vars
        run: |
          echo "Deploying to prod..."
