name: 16 - Working with Environments

on:
  workflow_dispatch:
    inputs:
      target-env:
        description: 'target-env'
        type: environment
        default: 'staging'

# Set the run-name dynamically using the target-env input
run-name: 16 - Working with Environments | env - ${{ github.event.inputs.target-env }}

jobs:
  echo:
    runs-on: ubuntu-latest

    # Set the environment parameter dynamically based on the target-env input
    environment: ${{ github.event.inputs.target-env }}

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Define environment variable and echo it
      - name: Echo vars
        run: |
          echo "Env variable: ${{ env.my_env_value }}"
        env:
          # Dynamically set my_env_value based on the selected environment (prod or staging)
          my_env_value: ${{ github.event.inputs.target-env == 'prod' && secrets.MY_ENV_VALUE_PROD || github.event.inputs.target-env == 'staging' && secrets.MY_ENV_VALUE_STAGING || 'default value' }}
